stages:
  - testing
  - push_report

variables:
  DOCKER_IMAGE: "ruby-tests-custom"
  REPORT_PATH: "test_reports"
  TZ: "Europe/Moscow"

build-and-test:
  stage: testing
  before_script:
    - export TEST_PATH=$(python3 ./get_path.py "$CI_COMMIT_TITLE")
    - export TEST_NAME=$(basename "$TEST_PATH" .rb)
    - mkdir -p $REPORT_PATH
  script:
    - docker container prune -f
    - docker rmi creatior3/ruby-tests:latest 2>/dev/null || true
    - docker rmi $DOCKER_IMAGE 2>/dev/null || true
    - docker build -t $DOCKER_IMAGE .

    - docker run --rm -v $(pwd)/$REPORT_PATH:/app/report $DOCKER_IMAGE ./$TEST_PATH

    - |
      PASSED=$(grep -q '100% passed' $REPORT_PATH/index.html && echo "1" || echo "0")

    - |
      TAG=$(echo "$CI_COMMIT_TITLE" | grep -oE "L[0-9]+ T[0-9]+(\.[0-9]+)?" || true)
      if [ -z "$TAG" ]; then
        TAG="UNKNOWN"
      fi
      TAG_UNDERSCORED=${TAG// /_}

    - |
      set +e
      COUNT=$(ls $REPORT_PATH/report_*_${TAG_UNDERSCORED}*.html 2>/dev/null | wc -l)
      set -e
      INDEX=$((COUNT + 1))

    - |
      REPORT_NAME="report_${INDEX}_${TAG_UNDERSCORED}"
      if [ "$PASSED" -eq 1 ]; then
        REPORT_NAME="${REPORT_NAME}_PASSED"
      fi
      REPORT_NAME="${REPORT_NAME}.html"

    - mv $REPORT_PATH/index.html $REPORT_PATH/$REPORT_NAME
    - echo $REPORT_NAME > $REPORT_PATH/report_name.txt
  artifacts:
    paths:
      - $REPORT_PATH
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test"'

push-report:
  stage: push_report
  script:
    - git config user.name "CI Bot"
    - git config user.email "ci-bot@example.com"

    - git config pull.rebase false

    - git checkout $CI_COMMIT_BRANCH
    - git pull

    - export REPORT_NAME=$(cat $REPORT_PATH/report_name.txt)
    - git add "$REPORT_PATH/$REPORT_NAME"
    - rm -f $REPORT_PATH/report_name.txt $REPORT_PATH/test_path.txt
    - git commit -m "Добавлен HTML-отчет о тестировании [skip ci]" || echo "No changes to commit"
    - git push https://${GITLAB_USERNAME}:${PRIVATE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test"'
  needs:
    - job: build-and-test
