stages:
  - testing
  - push_report

variables:
  DOCKER_IMAGE: "ruby-tests-custom"
  REPORT_PATH: "test_reports"
  TZ: "Europe/Moscow"

build-and-test:
  stage: testing
  before_script:
    - export TEST_PATH=$(python3 ./get_path.py "$CI_COMMIT_TITLE")
    - mkdir -p $REPORT_PATH
  script:
    - docker container prune -f
    - docker rmi creatior3/ruby-tests:latest 2>/dev/null || true
    - docker rmi $DOCKER_IMAGE 2>/dev/null || true
    - docker build -t $DOCKER_IMAGE .
    - chmod +x ./run_tests.sh
    - ./run_tests.sh "$DOCKER_IMAGE" "$REPORT_PATH" "$TEST_PATH" "$CI_COMMIT_TITLE"
  artifacts:
    paths:
      - $REPORT_PATH
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test"'

push-report:
  stage: push_report
  script:
    - git config user.name "CI Bot"
    - git config user.email "ci-bot@example.com"
    - git config pull.rebase false
    - git checkout $CI_COMMIT_BRANCH
    - git pull
    - export REPORT_NAME=$(cat $REPORT_PATH/report_name.txt)
    - git add "$REPORT_PATH/$REPORT_NAME"
    - rm -f $REPORT_PATH/report_name.txt $REPORT_PATH/test_path.txt
    - git commit -m "Добавлен HTML-отчет о тестировании [skip ci]" || echo "No changes to commit"
    - git push https://${GITLAB_USERNAME}:${PRIVATE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:$CI_COMMIT_BRANCH
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test"'
  needs:
    - job: build-and-test